getready = "Hello! Please prepare yourself, your trade is about to begin."
failed = "Failed to connect and trade with user."
success = "Here is what you traded to me:"
errormessage = "An error has occured while processing your request. Please try again."
lgpe = "SysBot.py is not made for LGPE yet."
swsh = "SysBot.py is not made for SWSH yet."